/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "NSCoding.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class NSString, CLGeocoder, NSDate, NSDictionary;

@interface _MPMeCardGeocoderAddress : XXUnknownSuperclass <NSCoding> {
	NSDictionary* _addressDictionary;
	NSString* _entityID;
	NSString* _label;
	CLGeocoder* _geocoder;
	int _state;
	int _tries;
	NSDate* _lastGeocodeAttempt;
	NSDictionary* _locationDictionary;
	BOOL _cancelingGeocode;
	NSDate* _geocodeAfter;
}
@property(readonly, assign) NSDate* geocodeAfter;
@property(readonly, assign) int state;
@property(readonly, assign) NSDate* lastGeocodeAttempt;
@property(readonly, assign) NSDictionary* locationDictionary;
@property(readonly, assign) NSDictionary* addressDictionary;
-(id)description;
-(BOOL)expired;
-(id)nextGeocodeAttempt;
-(void)cancelGeocode;
-(void)attemptGeocodeWithCompletionBlock:(id)completionBlock;
-(void)recalculateGeocodeAfterDate;
-(BOOL)checkGeocodeAfterDateForSanity;
-(id)createGeocodeAfterDate;
-(void)dealloc;
-(void)encodeWithCoder:(id)coder;
-(id)initWithCoder:(id)coder;
-(id)initWithAddressDictionary:(id)addressDictionary entityID:(id)anId label:(id)label;
@end

