/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSDictionary;

@interface _MPMeCardGeocoderPreferences : XXUnknownSuperclass {
	NSDictionary* _defaultValues;
	NSDictionary* _currentValues;
}
+(id)sharedPreferences;
-(void)_networkDefaultsRegistrationComplete:(id)complete;
-(BOOL)hasValidNetworkPreferences;
-(double)activeUsagePeriodLength;
-(double)periodLength;
-(double)_bestTimeIntervalForKey:(id)key;
-(id)_constructCurrentValues;
-(void)dealloc;
-(id)init;
@end

