/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "NSObject.h"


@protocol ABPredicateDelegate <NSObject>
-(BOOL)predicateShouldContinue:(id)predicate afterFindingRecord:(void*)record;
-(BOOL)predicateShouldContinue:(id)predicate;
@end

