/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSString;
@protocol MPDeclineAndReplyViewControllerDelegate;

@interface MPDeclineAndReplyViewController : XXUnknownSuperclass {
	id _readyToPresentHandler;
	NSString* _sentBody;
	id<MPDeclineAndReplyViewControllerDelegate> _declineAndReplyViewControllerDelegate;
}
@property(assign) id<MPDeclineAndReplyViewControllerDelegate> declineAndReplyViewControllerDelegate;
@property(readonly, assign) NSString* sentBody;
-(void)dealloc;
-(void)smsComposeControllerSendStarted:(id)started withText:(id)text;
-(void)smsComposeControllerDataInserted:(id)inserted;
-(void)smsComposeControllerWasSilent:(id)silent;
-(void)startWithReadyHandler:(id)readyHandler;
-(void)setCanEditRecipients:(BOOL)recipients;
@end

