/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "NSObject.h"


@protocol MPDeclineAndReplyViewControllerDelegate <NSObject>
@optional
-(void)messageComposeViewController:(id)controller messageBodyChanged:(id)changed;
@end

