/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library


@interface MPDeclineAndReplyActionSheet : XXUnknownSuperclass {
	BOOL _suppressSlideOut;
}
@property(assign) BOOL suppressSlideOut;
-(void)_slideSheetOut:(BOOL)anOut;
@end

