/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "MPIncomingFaceTimeCallController.h"


@interface MPFaceTimeCallWaitingController : MPIncomingFaceTimeCallController {
	int _backgroundType;
}
@property(assign, nonatomic) int backgroundType;
@property(readonly, assign, nonatomic) BOOL showDoubleButtonTopBar;
-(void)lockBarUnlocked:(id)unlocked;
-(id)newBottomBar;
-(id)_newBottomButtonBar;
-(id)newTopBar;
-(id)_newTopButtonBar;
-(void)decline;
-(void)accept;
-(BOOL)handleHeadsetButtonPressed:(BOOL)pressed;
-(void)_updateBackgroundViewForCurrentBackgroundType;
-(void)_updateBackgroundType;
-(BOOL)hasTranslucentBackground;
-(void)showBackgroundViewAnimated:(BOOL)animated;
-(id)backgroundView;
-(id)defaultBackgroundView;
-(void)viewDidLoad;
-(BOOL)shouldZoomOutBackgroundView;
-(void)updateImageFromPerson:(void*)person;
-(void)updateTopBarWithName:(id)name image:(id)image;
-(void)_updateDisplayControllerForOrientation:(int)orientation;
-(id)additionalURLQueryParameters;
-(int)deactivationStyle;
-(BOOL)isShowingWallpaper;
-(void)_handleCanceledInvitation:(id)invitation;
-(void)dealloc;
-(id)initWithHandle:(id)handle conferenceID:(id)anId;
@end

