/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "IncomingCall-Structs.h"
#import "MPIncomingPhoneCallController.h"

@class UIView;

@interface MPIncomingPhoneCallDuringFaceTimeController : MPIncomingPhoneCallController {
	UIView* _wallpaperView;
	BOOL _hideWallpaperView;
}
-(void)lockBarUnlocked:(id)unlocked;
-(void)_callCountChanged:(id)changed;
-(id)newBottomBar;
-(id)_newBottomButtonBar;
-(void)viewDidUnload;
-(void)viewDidLoad;
-(void)loadView;
-(void)updateImageFromPerson:(void*)person;
-(void)endAndAnswer:(id)answer;
-(BOOL)handleLockButtonPressed;
-(void)ignore;
-(void)requestDeactivation;
-(int)deactivationStyle;
-(BOOL)hasTranslucentBackground;
-(BOOL)isShowingWallpaper;
-(id)additionalURLParameter;
-(id)defaultBackgroundView;
-(void)dealloc;
-(id)initWithCall:(CTCallRef)call;
@end

