/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "TPIncomingCallOptionsViewDelegate.h"
#import "UIActionSheetDelegate.h"
#import <XXUnknownSuperclass.h> // Unknown library
#import "MFMessageComposeViewControllerDelegate.h"
#import "MPDeclineAndReplyViewControllerDelegate.h"
#import "CLLocationManagerDelegate.h"

@class MPDeclineAndReplyViewController, TPIncomingCallOptionsScrollView, UIActionSheet, NSArray, TUReplyWithMessageStore, MPDeclineAndReplyActionSheet, TPAlertViewHelper, CLLocationManager, NSNumber, NSString;

@interface MPIncomingCallController : XXUnknownSuperclass <TPIncomingCallOptionsViewDelegate, UIActionSheetDelegate, MFMessageComposeViewControllerDelegate, MPDeclineAndReplyViewControllerDelegate, CLLocationManagerDelegate> {
	TPIncomingCallOptionsScrollView* _scrollView;
	UIActionSheet* _remindActionSheet;
	NSString* _remindActionSheetNumber;
	NSString* _remindActionSheetName;
	NSNumber* _remindActionSheetABUID;
	NSArray* _remindActionSheetLocations;
	MPDeclineAndReplyActionSheet* _cannedResponseActionSheet;
	NSString* _cannedResponseActionSheetNumber;
	NSString* _cannedResponseActionSheetName;
	NSNumber* _cannedResponseActionSheetABUID;
	MPDeclineAndReplyViewController* _composeController;
	TUReplyWithMessageStore* _replyWithMessageStore;
	BOOL _didShowComposeSheet;
	BOOL _lockScreenMessagingAllowed;
	void* _addressBook;
	TPAlertViewHelper* _remindAmbiguousAlertViewHelper;
	CLLocationManager* _locationManager;
	id _locationAuthorizationStatusCallback;
}
+(id)optionsAnswerIconPressed;
+(id)optionsAnswerIcon;
+(id)optionsDeclineIconPressed;
+(id)optionsDeclineIcon;
-(void)didShowReminderOptions;
-(void)didShowComposeSheet;
-(id)urlForIncomingCallNumber:(id)incomingCallNumber;
-(id)reminderTextFormat;
-(void)handleOptionsSheetIgnoreWithDismiss:(BOOL)dismiss;
-(void)handleOptionsSheetAnswer;
-(id)incomingCallABUID;
-(id)incomingCallName;
-(id)incomingCallNumberQualifiedForMessages;
-(id)incomingCallNumber;
-(void)stopSuppressionOfSTKAlerts;
-(void)startSuppressionOfSTKAlerts;
-(void)actionSheet:(id)sheet clickedButtonAtIndex:(int)index;
-(void)_cannedResponseActionSheetClickedButtonAtIndex:(int)index;
-(void)_sendCannedResponse:(id)response;
-(void)_remindActionSheetClickedButtonAtIndex:(int)index;
-(void)createReminderForWhenILeave;
-(void)createReminderForLocation:(id)location;
-(void)createReminderWithDurationInMinutes:(int)minutes;
-(void)locationManager:(id)manager didChangeAuthorizationStatus:(int)status;
-(void)_cleanUpActionSheetVariables;
-(void)messageComposeViewController:(id)controller didFinishWithResult:(int)result;
-(void)_releaseAddressBook;
-(void*)sharedAddressBook;
-(void)_revertAddressBook;
-(void)incomingOptionsViewDeclinedCall:(id)call;
-(void)incomingOptionsViewAcceptedCall:(id)call;
-(void)viewWillAppear:(BOOL)view;
-(void)viewWillDisappear:(BOOL)view;
-(void)viewDidLoad;
-(void)incomingOptionsView:(id)view selectedItem:(int)item;
-(void)showCustomReplyWithMessageUI;
-(BOOL)allowStackingOfAlert:(id)alert;
-(id)iconOfItemForView:(id)view atIndex:(int)index forPressedState:(BOOL)pressedState;
-(id)nameOfItemForView:(id)view atIndex:(int)index;
-(int)numberOfItemsForView:(id)view;
-(id)locationManager;
-(void)createOptionsScrollView;
-(id)replyWithMessageStore;
-(BOOL)canRemind;
-(BOOL)canMessage;
-(BOOL)isLockScreenMessagingAllowed;
-(BOOL)areIncomingCallOptionsAllowed;
-(void)dismissOptionsViewRelatedUI;
-(BOOL)showingOptionsViewRelatedUI;
-(void)requestDeactivationAnimated:(BOOL)animated animateOldDisplayInWithStyle:(int)style;
-(void)requestActivationAnimated:(BOOL)animated animateCurrentDisplayOut:(BOOL)anOut withDelay:(BOOL)delay;
-(BOOL)handleMenuButtonTap;
-(void)dealloc;
-(id)init;
@end

