/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library


@interface MPIncomingCallUtilities : XXUnknownSuperclass {
}
+(id)imageForPerson:(void*)person isFullscreen:(BOOL*)fullscreen;
+(id)wallpaperViewWithImage:(id)image;
@end

