/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSObject, NSMutableArray, PCPersistentTimer;
@protocol OS_dispatch_queue;

@interface MPMeCardGeocoder : XXUnknownSuperclass {
	void* _addressBook;
	NSObject<OS_dispatch_queue>* _workQueue;
	NSMutableArray* _addresses;
	PCPersistentTimer* _networkPreferencesTimeoutTimer;
}
@property(assign) BOOL isActivelyUsing;
+(id)sharedMeCardGeocoder;
-(void)_addressBookChanged;
-(id)currentValidLocations;
-(void)_rebuildAddressArray;
-(void)_scheduleLongTermRebuild;
-(id)_dateOfOldestAddress;
-(void)_unscheduleLongTermRebuild;
-(void)_scheduleNextGeocode;
-(void)_schedulePerformGeocodesTaskWithStartWakeTime:(id)startWakeTime dropDeadWakeTime:(id)time;
-(BOOL)_unschedulePerformGeocodesWakeTaskIfEarlierThan:(id)than;
-(void)_doWork;
-(void)_saveGeoCache;
-(void)scheduleNextGeocode;
-(void)scheduleImmediateGeocode;
-(BOOL)_isNetworkAvailable;
-(void*)addressBook;
-(void)dealloc;
-(void)_networkPreferencesLoaded;
-(id)init;
@end

