/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "IncomingCall-Structs.h"
#import "MPIncomingPhoneCallController.h"

@class TPIncomingCallOptionsView, TPCallWaitingButton;

@interface MPPhoneCallWaitingController : MPIncomingPhoneCallController {
	TPCallWaitingButton* _ignoreButton;
	TPCallWaitingButton* _answerButton;
	TPIncomingCallOptionsView* _animatingBottomBar;
	unsigned _didRelease : 1;
	unsigned _didHeldRelease : 1;
	unsigned _setupForThree : 1;
	BOOL _forceShowCallWaitingUI;
}
-(void)lockBarUnlocked:(id)unlocked;
-(void)_tearDown;
-(void)_callCountChanged:(id)changed;
-(void)_addCallWaitingButtons:(BOOL)buttons;
-(id)_getButtonFromBar:(id)bar;
-(void)getFrameForTopButton:(CGRect*)topButton bottomButton:(CGRect*)button;
-(id)newBottomBar;
-(id)_newBottomButtonBar;
-(void)incomingOptionsView:(id)view selectedItem:(int)item;
-(id)iconOfItemForView:(id)view atIndex:(int)index forPressedState:(BOOL)pressedState;
-(id)nameOfItemForView:(id)view atIndex:(int)index;
-(int)numberOfItemsForView:(id)view;
-(void)incomingOptionsView:(id)view revealedPixels:(int)pixels percentage:(float)percentage;
-(void)incomingOptionsViewCallWaitingButtonClicked:(id)clicked;
-(void)handleOptionsSheetIgnoreWithDismiss:(BOOL)dismiss;
-(BOOL)_shouldBeShowingCallWaitingUI;
-(void)viewDidLoad;
-(void)updateImageFromPerson:(void*)person;
-(void)ignore;
-(void)requestDeactivation;
-(BOOL)deactivateAnimated;
-(int)deactivationStyle;
-(void)endAllCalls:(id)calls;
-(void)answerAndRelease:(id)release;
-(BOOL)handleLockButtonPressed;
-(void)answerCall:(CTCallRef)call;
-(void)dealloc;
-(id)additionalURLParameter;
@end

