/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SBPluginBundleController.h"
#import "IncomingCall-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library


@interface MPTelephonyManager : XXUnknownSuperclass <SBPluginBundleController> {
}
+(void)awakeFromBundle;
+(void)_setupQuietHours;
+(id)sharedInstance;
-(void)displayAlertForCall:(CTCallRef)call;
-(BOOL)isTTYEnabled;
-(BOOL)inCall;
-(BOOL)incomingCallExists;
-(BOOL)heldCallExists;
-(BOOL)activeCallExists;
-(int)callCount;
-(id)init;
@end

