/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */



@protocol TPBottomLockBarDelegate
-(void)lockBarUnlocked:(id)unlocked;
@optional
-(void)lockBar:(id)bar textAlphaChangedForKnobDrag:(float)knobDrag;
-(void)lockBarSlidBackToOrigin:(id)origin;
-(void)lockBarStoppedTracking:(id)tracking;
-(void)lockBarStartedTracking:(id)tracking;
@end

